spring.application.name=api-tienda

spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

spring.datasource.url=jdbc:tc:postgresql:16:///lms_db

spring.datasource.username=test
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=${JWT_EXPIRATION:3600}